# Generated by Django 5.1.1 on 2024-09-27 07:03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.CharField(default='', max_length=6, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
                ('age', models.CharField(default='', max_length=100)),
                ('weight', models.CharField(default='', max_length=100)),
                ('mobile_number', models.CharField(default='', max_length=10)),
                ('Complain', models.CharField(default='', max_length=200)),
                ('BP', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('PR', models.CharField(default='', max_length=3)),
                ('SPO2', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Temp', models.FloatField(default=0)),
                ('Advice', models.CharField(default='', max_length=200)),
                ('Medicine', models.CharField(default='', max_length=200)),
                ('Duration', models.CharField(default='', max_length=200)),
                ('Days', models.CharField(default='', max_length=20)),
                ('Online_payment', models.CharField(default='', max_length=255)),
                ('Cash_payment', models.CharField(default='', max_length=255)),
                ('Balance_amount', models.CharField(default='', max_length=255)),
                ('Total_amount', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
