# Generated by Django 5.1.1 on 2024-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Paid_amount',
            field=models.CharField(default='', max_length=255),
        ),
    ]
