# Generated by Django 5.1.1 on 2024-10-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
